name: Proselint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install proselint
      - run: proselint check $(git ls-files '*.md')
